FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY src/TrainingOrchestrator.Controller/ ./TrainingOrchestrator.Controller/
WORKDIR /src/TrainingOrchestrator.Controller
RUN dotnet publish -c Release -o /app

FROM mcr.microsoft.com/dotnet/runtime:8.0
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "TrainingOrchestrator.Controller.dll"]
